# Generated by Django 5.0.6 on 2025-09-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('cartao', 'Cartão de Crédito/Débito')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefone_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
