"""
Django settings for djangoapp project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

from pathlib import Path
import os

# -------------------------------
# Paths
# -------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------
# Segurança
# -------------------------------
SECRET_KEY = 'django-insecure-#%=yf$x+s9+)tb_te*tv^ld-7@t%4o7!vme(tykd!ij@7k5ca+'
DEBUG = True
ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = [
    'https://8000-firebase-loja-de-roupoas-1755007587756.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev'
]

# -------------------------------
# Aplicativos instalados
# -------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'usuario.apps.UsuarioConfig',   # Apenas esta linha para o app usuario
    'produtos.apps.ProdutosConfig', # Assumindo que ProdutosConfig existe
    'carrinho.apps.CarrinhoConfig', # Assumindo que CarrinhoConfig existe
    'pedidos.apps.PedidosConfig',   # Assumindo que PedidosConfig existe
]

# Se você tem CustomUser
AUTH_USER_MODEL = 'usuario.CustomUser'

# -------------------------------
# Middleware
# -------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoapp.urls'

# -------------------------------
# Templates
# -------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapp.wsgi.application'

# -------------------------------
# Banco de dados
# -------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------
# Validação de senhas
# -------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# -------------------------------
# Internacionalização
# -------------------------------
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = False

# -------------------------------
# Arquivos estáticos e mídia
# -------------------------------
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# -------------------------------
# Default primary key field
# -------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
