# Generated by Django 5.2.5 on 2025-09-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_produto_carrinho_profile_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='fotos_perfil/avatar_default.png', upload_to='fotos_perfil/'),
        ),
    ]
